### ISSUE TITLE
autodoc(file) giving error: UndefVarError: get_args not defined

### ISSUE THREAD

**Issue by rphillips31** [baggepinnen/AutomaticDocstrings.jl#11]
Greetings,

Started to get some documentation together and I get the error _UndefVarError: get_args not defined__ when I run in the REPL using autodoc("my_file.jl"). I'm a little stuck as to next steps. Any advice?
The full stacktrace is:

Stacktrace:
 [1] getproperty 
   @ ./Base.jl:26 [inlined]  
 [2] get_args(parseddef::CSTParser.EXPR)
   @ AutomaticDocstrings ~/.julia/packages/AutomaticDocstrings/Ob8ZM/src/AutomaticDocstrings.jl:80
 [3] get_function_definition(file::String, li::Int64)
   @ AutomaticDocstrings ~/.julia/packages/AutomaticDocstrings/Ob8ZM/src/AutomaticDocstrings.jl:75
 [4] generate_docstring(file::String, li::Int64)
   @ AutomaticDocstrings ~/.julia/packages/AutomaticDocstrings/Ob8ZM/src/AutomaticDocstrings.jl:50
 [5] autodoc(file::String)
   @ AutomaticDocstrings ~/.julia/packages/AutomaticDocstrings/Ob8ZM/src/AutomaticDocstrings.jl:38
 [6] top-level scope
   @ REPL[4]:1

What's weird is that the code is failing to find get_args in line 80, but that function is defined a little further down in line 95. I'm trying to use the autodoc() function to generate docstubs that will eventually get pulled out with Documenter.jl if that helps.

**Comment by baggepinnen** [comment]
Are you using the latest version of this package? I fixed some stuff related to that function just a few days ago, maybe you need to update?

**Comment by rphillips31** [comment]
Looks like that did the trick. Didn't notice you had pushed an update. Thanks again. Great module!
