### ISSUE TITLE
Option to include the arg types in the doc string

### ISSUE THREAD

**Issue by ValentinKaisermayer** [baggepinnen/AutomaticDocstrings.jl#12]
It would be nice to have the option to include the argument types in the list.

Expected output:
```julia
SIGNATURE

DOCSTRING

# Arguments:
- `arg1::argtype1`: DESCRIPTION
- `arg2::argtype2`: DESCRIPTION
```

BTW nice package 👍

**Comment by ValentinKaisermayer** [comment]
Should be very easy, since MarcoTools already does the parsing:
https://github.com/FluxML/MacroTools.jl/blob/5e0fe08c0c8b4ab61989b187f5a151e2ec95541d/src/utils.jl#L435

**Comment by baggepinnen** [comment]
This would be a nice feature to have. Currently, the signature is copied exactly, so if we add types to the argument list, perhaps the types should be removed from the signature?
